[tool.poetry]
name = "script-profits"
version = "0.1.0"
description = ""
authors = ["r-spiewak <63987228+r-spiewak@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "script-profits", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
typer = "^0.12.3"
pandas = "^2.2.2"


[tool.poetry.scripts]
script-profits = 'script-profits.run:run'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
